### ISSUE TITLE
R package `cli` needed for WEPPCLIFF to run on RHEL8  / R 3.6.3

### ISSUE THREAD

**Issue by akrherz** [ryanpmcg/WEPPCLIFF#17]
Attempting to run WEPPCLIFF on Red Hat Linux 8 x64 using R 3.6.3 required the `cli` package to also be installed.

```
$ /opt/R-3.6.3/bin/Rscript --vanilla WEPPCLIFF.R --args -f 096.40x043.17.txt -la y
...
Processing station... Error in loadNamespace(name) : there is no package called ‘cli’
Calls: main ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
...
```

I R `install.packages('cli')` and got past this issue.

**Comment by ryanpmcg** [comment]
@akrherz can you clarify whether the installation tried and failed to get 'cli' or that it never attempted to get it? Packages in R are supposed to install their own dependencies first as part of installation. I am a little surprised if this did not happen here?

**Comment by akrherz** [comment]
@ryanpmcg Thanks for the response.  I attempted to reproduce this by

1. Blowing out the `LIBRARY` folder
2. Running `sh INSTALLER/Install.sh >& install.log` and you can see that file [here](https://github.com/ryanpmcg/WEPPCLIFF/files/5419567/install.zip)
3. Did not see anything interesting in `install.log` regarding the `cli` package.
4. Observing no cli folder in `LIBRARY` folder

**Comment by ryanpmcg** [comment]
@akrherz Ok, a couple things:
1. installation was successful, so any dependencies packages needed had to be installed to get that message.
2. the same test is used at the beginning of all WEPPCLIFF runs, so I don't know why it gave a success message here and not earlier. Do you still get that message? Did you get a success message the first time you installed dependencies?

**Comment by akrherz** [comment]
> Do you still get that message?

I did not check as I just installed `cli` again after the installer finished.  So I redid the procedure above again and wasn't able to reproduce the need for the `cli` package, le sigh.  Sorry for an apparent goose chase!

**Comment by ryanpmcg** [comment]
No problem. I am grateful to have someone helping improve the tool. The most common reason for installation failure is a brief lapse in connectivity resulting in a failed checksum test in installation. The fix is to just run the -fr t command again, but unless you saw the unsuccessful message at the end, a user may just try to run a typical WEPPCLIFF command because the message becomes lost in all the screen output during dependency installation.
