### ISSUE TITLE
Default directories are made when non default directories are specified

### ISSUE THREAD

**Issue by kbarnhart** [ryanpmcg/WEPPCLIFF#3]
Another issue associated with the JOSS review openjournals/joss-reviews/issues/2029

I tried out some of the non default directory names using one of the basic examples. 

I renamed INPUTS to SPAM and ran:

```
Rscript --vanilla WEPPCLIFF.R --args -f ASOS_BPT_KMQE.csv -d SPAM  -o EGGS
```

I was surprised to find that empty directories called INPUT and OUTPUT were still created.

**Comment by ryanpmcg** [comment]
INPUT and OUTPUT are part of a base directory structure created (if they do not exist) in every WEPPCLIFF run. The same is true for the other base directory folders. I can change the behavior to create only the specified folders.

**Comment by kbarnhart** [comment]
I find the extraneous directories created confusing. For example if a directory called PLOT is created, but no plots are inside (because I didn't specify a run that creates plots, then I'm confused whether I specified the run wrong or whether a plot was supposed to be created but wasn't). A comment that is related to this and #2 is that if you run weppcliff outside of the main directory (I will respond with a recommendation on that on the #2 thread), a LIBRARY directory is created. 

I'd recommend only making output directories that are used. 

If this is difficult to implement, I'd recommend making very clear in the documentation that (insert list of directory names) is always created.

**Comment by ryanpmcg** [comment]
No problem at all. I made the changes, and added the functionality to place the library in a specified location now. The library needed to be specifiable to get past permission issues on some machines. If you find that it works, will you close this issue?
