### ISSUE TITLE
Improvements to documentation about input files

### ISSUE THREAD

**Issue by kbarnhart** [ryanpmcg/WEPPCLIFF#4]
@ryanpmcg A clarification about input file column requirements. I'm trying to imagine a variety of use cases based on weather station data I've used in the past. Based on this I tried out a couple of modifications to input files to see if I could figure out how to do something using the documentation. By and large I find the documentation comprehensive and clear, but there were a few things that I tried that helped me identify improvements to description of the input files.

I found the part of the documentation on variable names (pg 25) and the table of input format conventions (pg 21) but I couldn't figure out what subset of variable names are required. My best guess is that everything in the table of input formats is required and that LAT, LON, and STATION are optional, but I think this should be stated explicitly. 

### Part 1: 
So I tried a duck test... I replaced PRECIP W_VEL and STATION with EGGS in in INPUT/ASOS_BPT_KMQE.csv and ran 

Rscript --vanilla WEPPCLIFF.R --args -f ASOS_BPT_KMQE.csv

I got no error for STATION but (not surprisingly) errors for the other two (e.g., Processing station... Some expected variables are missing: W_VEL).

Based on this I have three recommendations:

1. I'd recommend that you expand the documentation to indicate which WEPPCLIFF variable header names are required inputs and which are optional. 

2.  I'd also recommend some sort of warning that indicates that variables in the input are being ignored (I presume that when I replaced STATION with EGGS, that WEPPCLIFF assumed that the input file was a single station and ignored EGGS, LAT, and LON). 

3. The input section does not include information about the expected formats of LAT, LON, and STATION. I recommend stating this somewhere in the input or referring to the list on pg 25. In that list I see DD (which I know is decimal degrees), but I recommend writing it out. 

### Part 2:
Then I wondered if I had a hypothetical weather station with all the data on the same timestamp, would I need to provide DT_1, DT_2, and DT_3 as equivalent columns. I tried making a modification of AH537_15MIN.csv that removed the DT_3 column and found that this did not work.

Recommendations: 
1. If there is any mechanism by which one might say that all three timestamps are the same, I'd recommend it be more clear.

**Comment by kbarnhart** [comment]
Linking to the review issue:  openjournals/joss-reviews/issues/2029

**Comment by ryanpmcg** [comment]
I have just updated the documentation with all this new information. At present, there is no mechanism for providing only one DT input for all variables. It is rare to have the same temporal resolution for all those variables. The nice thing is that you can copy the column, change the header name, and WEPPCLIFF assumes the same date time format for all 3 (based on DT_1) unless specified otherwise. So, at least that is supported.

**Comment by kbarnhart** [comment]
@ryanpmcg sounds good. I looked at the revised documentation and it looks like these issues are adequately addressed. 👍
