### ISSUE TITLE
All CLI test pass but all RDS tests fail

### ISSUE THREAD

**Issue by kbarnhart** [ryanpmcg/WEPPCLIFF#7]
https://github.com/openjournals/joss-reviews/issues/2029

I ran the autotestst and got the following result:
 Passed CLI Test 1
 Failed RDS Test 1
 Passed CLI Test 2
 Failed RDS Test 2
 Passed CLI Test 3
 Failed RDS Test 3
 Passed CLI Test 4
 Failed RDS Test 4
 Passed CLI Test 5
 Failed RDS Test 5
 Passed CLI Test 6
 Failed RDS Test 6
 Passed CLI Test 7
 Failed RDS Test 7
 Passed CLI Test 8
 Failed RDS Test 8

I'm using R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night" on OS X 10.12.3. 

I haven't used R extensively in the last year (and had my computer wiped between now and then), so my R install was new for WEPPCLIFF.  

Let me know what I can provide to help diagnose this.

**Comment by ryanpmcg** [comment]
Failing the RDS test is not as important as the CLI test. The CLI test is testing only for human readable differences. The RDS is testing for differences in any internal calculations and those are all stored in binary.

With that said, I still care about the potential differences internally, and to know what is different, I would need the .rds files from your auto test run. They are saved in the auto test folder under OUTPUT.

**Comment by kbarnhart** [comment]
I re-ran the tests today after a fresh install (and without any of the changes I proposed on #8), and now everything fails 😞 . I've attached all the files as a .zip of the OUTPUT folder.

[OUTPUT.zip](https://github.com/ryanpmcg/WEPPCLIFF/files/4435258/OUTPUT.zip)

**Comment by ryanpmcg** [comment]
I am sorry. I was probably updating it at the same time you were using it. I had to go through all the changes to make sure it was consistent, and there were many small changes in the benchmarks. It should be better now.

**Comment by ryanpmcg** [comment]
To be clear, I am still not too optimistic about the .rds files. They may never be the same between different operating systems. I never was able to get them identical between OSX and Windows (though I tried to find any differences within).

The .cli test is important, and my plan is to just run the .rds tests quietly while using the .cli tests as the main test.

**Comment by kbarnhart** [comment]
@ryanpmcg not a problem. I just re-ran them and got the following. 
```
 Failed CLI Test 1
 Failed RDS Test 1
 Passed CLI Test 2
 Failed RDS Test 2
 Passed CLI Test 3
 Failed RDS Test 3
 Passed CLI Test 4
 Failed RDS Test 4
 Passed CLI Test 5
 Failed RDS Test 5
 Passed CLI Test 6
 Failed RDS Test 6
 Passed CLI Test 7
 Failed RDS Test 7
 Passed CLI Test 8
 Failed RDS Test 8
```
Mac OS 10.15.2
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
WEPPCLIFF on commit 35de67dd89ca56a66304365375f621563a6199a8

A zip of WEPPCLIFF/AUTOTEST/OUTPUT attached. 
[OUTPUT.zip](https://github.com/ryanpmcg/WEPPCLIFF/files/4439662/OUTPUT.zip)

Let me know when/if you want me to try again.

**Comment by ryanpmcg** [comment]
I found 'an' issue causing differences in the comparisons. I have learned when working with code that an error means exactly the following: there is at least one error.

The files you sent are offset by 2 hours. I am in the Eastern US time zone, and I suppose you are on Mountain time. That would explain why all my testing would not detect it...all the machines were in the same time zone. So all .rds comparisons will fail on account of different dates, and the longer files (the first .rds and .cli test) will result in different calculations from the offset.

I am unsure about the best way to resolve it at the present, and it will take some time for me to learn what to do. I will start searching.

**Comment by kbarnhart** [comment]
@ryanpmcg you are correct that I'm in mountain time. One thought (that may or may not be relevant) is to provide the ability to specify the time zone as a date time control argument. The default might be the user's local timezone. 

Just let me know when you'd like me to try running the tests again.

**Comment by ryanpmcg** [comment]
@kbarnhart I haven't forgotten about this. I have had some other pressing business come up that has greater urgency. When I make the changes to the R code, I will ask you to rerun it with those changes. I also plan to incorporate your [pull request](https://github.com/ryanpmcg/WEPPCLIFF/pull/8). Please attach your output when you run it if the .rds comparisons still fail. If I cannot find what is causing the issue after examining the .rds files, I plan to remove the .rds tests because the issue may be OS related.

**Comment by kbarnhart** [comment]
@ryanpmcg no worries. I'm in no rush and will plan to re-run whenever you want.

**Comment by ryanpmcg** [comment]
@kbarnhart I have a new branch with the update. I think I was able to do this on the third attempt. This branch also includes some other updates I plan to roll into the master as well (e.g. alias for UNIX machines, smarter directory path for Windows, should only create directories as needed, etc.)

**Comment by kbarnhart** [comment]
Is there a branch you want me to test at this point?

**Comment by ryanpmcg** [comment]
@kbarnhart, I have tested the new script on my Windows machines and now the CLI and RDS files are identical. It was related to the system environment settings and impacting date times, which impacts other things in a time series tool. I merged the branch to the master just to keep it simpler for me. So please test the master branch when available.

**Comment by ryanpmcg** [comment]
Hopefully, this change also fixes the time zone issue.

**Comment by kbarnhart** [comment]
I did a clean install and got:
```
Passed CLI Test 1
  Failed RDS Test 1

  Passed CLI Test 2
  Failed RDS Test 2

  Passed CLI Test 3
  Failed RDS Test 3

  Passed CLI Test 4
  Failed RDS Test 4

  Passed CLI Test 5
  Failed RDS Test 5

  Passed CLI Test 6
  Failed RDS Test 6

  Passed CLI Test 7
  Failed RDS Test 7

  Passed CLI Test 8
  Failed RDS Test 8
```
This is on a Mac. I haven't gotten to trying things out on my PC...

Contents of WEPPCLIFF/AUTOTEST/OUTPUT attached 
[OUTPUT.zip](https://github.com/ryanpmcg/WEPPCLIFF/files/4555892/OUTPUT.zip)

**Comment by ryanpmcg** [comment]
Well, @kbarnhart, despite the checksum being different, the values stored in at least RDS 2 are exactly the same. I ran my own script in R to check each list and data.frame for differences. Everything checked out. So, I think that this is good enough. I have already update the AutoTest.sh script for UNIX to perform the RDS tests, report results, and still pass the test (if and only if all CLI tests pass). Here is the code I used to check the data frames between three sets (yours, mine, and benchmark): 

```
Sys.setenv(TZ = "GMT")

kb.rds = readRDS("/Users/ryanmcgehee/Software/WEPPCLIFF/AUTOTEST/KBOUTPUT/AutoTest.2.rds")
rm.rds = readRDS("/Users/ryanmcgehee/Software/WEPPCLIFF/AUTOTEST/OUTPUT/AutoTest.2.rds")
wc.rds = readRDS("/Users/ryanmcgehee/Software/WEPPCLIFF/AUTOTEST/BENCHMARKS/AutoTest.2.rds")

for (i in c(1,3:5,7,9:14)) {
     kb.df = kb.rds[[i]]
     rm.df = rm.rds[[i]]
     wc.df = wc.rds[[i]]
     print(sum(kb.df == rm.df, na.rm = T))
     print(sum(rm.df == wc.df, na.rm = T))}
```

**Comment by ryanpmcg** [comment]
FYI, DFs 2 and 6 are empty for this test, and element 8 is a list, which needs a different test.

**Comment by ryanpmcg** [comment]
If you run the new AutoTest.sh and think it is good enough, please close this issue.

**Comment by kbarnhart** [comment]
@ryanpmcg my thought is that I would be confused by an unexplained exit code. If the RDS tests aren't going to influence whether the tests pass or fail, I'd comment them out. Or at minimum state that an exit code of 0 on RDS means that the binary files are not the same but that is know to be based on system differences. 

You could also run the above script as the RDS test since it ultimately demonstrates what you care about (that the contents of the RDS are the same).

Whatever the case, I think it is fair to say that the CLI tests are sufficient as tests. 

@thatmushroom (my local R expert) thought that there might be a difference between the system md5 and the internal R md5 and that running md5 within R might solve the issue... In fact there was no difference. 
```
(base) barnhark@Katherines-MacBook-Pro WEPPCLIFF % md5 AUTOTEST/OUTPUT/AutoTest.1.rds
MD5 (AUTOTEST/OUTPUT/AutoTest.1.rds) = 367cdb2d4f48f81ce3a3f2cd326dc9ec
(base) barnhark@Katherines-MacBook-Pro WEPPCLIFF % md5 AUTOTEST/BENCHMARKS/AutoTest.1.rds
MD5 (AUTOTEST/BENCHMARKS/AutoTest.1.rds) = 3ccedaa3a5345579b959d7ab50d42f04
(base) barnhark@Katherines-MacBook-Pro WEPPCLIFF % R -q -e "library('tools'); md5sum('AUTOTEST/OUTPUT/AutoTest.1.rds')"
> library('tools'); md5sum('AUTOTEST/OUTPUT/AutoTest.1.rds')
    AUTOTEST/OUTPUT/AutoTest.1.rds
"367cdb2d4f48f81ce3a3f2cd326dc9ec"
>
>
(base) barnhark@Katherines-MacBook-Pro WEPPCLIFF % R -q -e "library('tools'); md5sum('AUTOTEST/BENCHMARKS/AutoTest.1.rds')"
> library('tools'); md5sum('AUTOTEST/BENCHMARKS/AutoTest.1.rds')
AUTOTEST/BENCHMARKS/AutoTest.1.rds
"3ccedaa3a5345579b959d7ab50d42f04"
>
>
(base) barnhark@Katherines-MacBook-Pro WEPPCLIFF %
```

**Comment by ryanpmcg** [comment]
@kbarnhart I will remove the exit codes and update the script and close this issue.
